---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  become: yes
  hosts: localhost
  roles:
    - common

- name: configure and deploy the webservers and application code
  become: yes
  hosts: localhost #webservers
  roles:
    - web

#- name: deploy MySQL and configure the databases
#  become: yes
#  hosts: all #dbservers
#  roles:
#    - db