---

- name: Conditional ansible test
  hosts: localhost
  tasks:
    - shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined
    - fail: msg="Bailing out. This play requires 'bar'"
      when: bar is undefined