# -*- mode: ruby -*-
# vi set ft=ruby :

servers=[
    {
        :hostname => "web-go",
        :ip => "192.168.100.10",
        :box => "ubuntu/xenial64",
        :ram => 1024,
        :cpu => 2,
        :provision => "sudo apt-get -y update \
            && sudo apt-get -y install git \
            && sudo apt-get -y update \
            && sudo curl -fsSL https://get.docker.com -o get-docker.sh \
            && sudo sh get-docker.sh \
            && sudo apt-get install -y python-pip \
            && sudo pip install docker-compose==1.17.1 \
            && sudo apt-get -y update \
            && sudo git clone https://github.com/guisesterheim/goMicroserviceWithETCD \
            && cd goMicroserviceWithETCD/ \
            && sudo docker-compose up -d"
    }
]

Vagrant.configure(2) do |config|

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.provision "shell", inline: machine[:provision]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end